kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: node:17
    commands:
      - npm install
      - npm run lint
      - npm run test:cov
      - npm run test:e2e
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
      files:
        - '*.json'
      paths:
        - coverage